#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

CONTAINER_ID=$(buildah from "$BASE_IMAGE")

function r () {
	buildah run "$CONTAINER_ID" -- "$@"
}

DIST=$HERE/work/dist

buildah copy "$CONTAINER_ID" "$HERE/assets/scripts/entrypoint" /bin/open5gs
buildah copy "$CONTAINER_ID" "$DIST/bin/"* /bin/
buildah_copy_recursive "$CONTAINER_ID" "$DIST/lib64" /lib64
# For webui
buildah_copy_recursive "$CONTAINER_ID" "$DIST/opt/open5gs-webui" /opt/open5gs-webui

r mkdir --parents /var/log/open5gs

cat <<- EOT > "$HERE/work/mongodb.repo"
	[MongoDB]
	name=MongoDB Repository
	baseurl=https://repo.mongodb.org/yum/redhat/8/mongodb-org/$MONGODB_REPOSITORY_VERSION/x86_64/
	gpgcheck=1
	enabled=1
	gpgkey=https://www.mongodb.org/static/pgp/server-$MONGODB_REPOSITORY_VERSION.asc
EOT

buildah copy "$CONTAINER_ID" "$HERE/work/mongodb.repo" /etc/yum.repos.d/

buildah copy "$CONTAINER_ID" "$(which kubectl)" /usr/bin/

# "gettext" for "envsubst"
# "iputils" for "ping"
# "mongodb-org-shell" for "mongo"

r dnf install --assumeyes \
	gettext iputils \
	mongodb-org-shell \
	mongo-c-driver \
	libidn \
	libmicrohttpd \
	lksctp-tools \
	usrsctp \
	npm
r dnf --assumeyes clean all

buildah config \
	--entrypoint /bin/open5gs \
	"$CONTAINER_ID"

buildah commit "$CONTAINER_ID" "localhost/$OPEN5GS_IMAGE_TAG"
