#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

BASE=$HERE/work/mongodb-kubernetes-operator

if [ ! -d "$BASE" ]; then
    m 'cloning repository...'
    git clone https://github.com/mongodb/mongodb-kubernetes-operator.git "$BASE" --depth 1
fi

m 'deploying MongoDB operator...'
kubectl apply --filename="$BASE/config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml"
kubectl apply --kustomize="$BASE/config/rbac/"
kubectl apply --filename="$BASE/config/manager/manager.yaml"
kubectl wait deployments/mongodb-kubernetes-operator --for=condition=Available
POD=$(kubectl get pods --selector=name=mongodb-kubernetes-operator --output=jsonpath={.items[0].metadata.name})
kubectl wait "pods/$POD" --for=condition=ContainersReady

if [ "$1" == -c ]; then
    m 'cleaning up...'
    kubectl delete mongodbcommunity --selector=app.kubernetes.io/part-of=open5gs --ignore-not-found=true
    kubectl wait statefulsets --selector=app=open5gs-mongodb-svc --for=delete || true
    kubectl wait pods --selector=app=open5gs-mongodb-svc --for=delete || true
    kubectl delete persistentvolumeclaims --selector=app=open5gs-mongodb-svc --ignore-not-found=true
    kubectl wait persistentvolumeclaims --selector=app=open5gs-mongodb-svc --for=delete || true
fi

m 'deploying... (may take some time!)'

VERSION=$OPEN5GS_VERSION \
MONGODB_VERSION=$MONGODB_VERSION \
envsubst < "$HERE/assets/kubernetes/mongodb.yaml" |
kubectl apply -f -

PHASE=
while [ "$PHASE" != Running ]; do
    PHASE=$(kubectl get mongodbcommunity open5gs-mongodb --output=jsonpath={.status.phase})
    echo -n .
    sleep 1
done
echo
