#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

if [ "$1" == -c ] || [ "$1" == -b ]; then
    m 'cleaning up...'
    kubectl delete deployments --selector=app.kubernetes.io/part-of=open5gs --ignore-not-found=true
    kubectl delete services --selector=app.kubernetes.io/part-of=open5gs --ignore-not-found=true
    kubectl delete rolebindings --selector=app.kubernetes.io/part-of=open5gs --ignore-not-found=true
    kubectl delete roles --selector=app.kubernetes.io/part-of=open5gs --ignore-not-found=true
    kubectl delete serviceaccounts --selector=app.kubernetes.io/part-of=open5gs --ignore-not-found=true
    kubectl wait pods --selector=app.kubernetes.io/part-of=open5gs --for=delete || true
    kubectl wait services --selector=app.kubernetes.io/part-of=open5gs --for=delete || true
fi

if [ "$1" == -b ]; then
    #"$HERE/build-binaries"
    "$HERE/build-container-image"
    "$HERE/publish-container-image"
fi

m 'deploying RBAC...'

VERSION=$OPEN5GS_VERSION \
envsubst < "$HERE/assets/kubernetes/rbac.yaml" |
kubectl apply -f -

m 'deploying services...'

VERSION=$OPEN5GS_VERSION \
envsubst < "$HERE/assets/kubernetes/services.yaml" |
kubectl apply -f -

m 'deploying components...'

function d () {
    if [ "$1" == webui ]; then
        local TEMPLATE=$HERE/assets/kubernetes/webui.yaml
    else
        local TEMPLATE=$HERE/assets/kubernetes/component.yaml
    fi

    VERSION=$OPEN5GS_VERSION \
    COMPONENT=$1 \
    REGISTRY=$(reposure registry info default host) \
    IMAGE_TAG=$OPEN5GS_IMAGE_TAG \
    envsubst < "$TEMPLATE" |
    kubectl apply -f -
}

d amf
d ausf
d bsf
d hss
d mme
d nrf
d nssf
d pcf
d pcrf
d sgwc
d sgwu
d smf
d udm
d udr
d upf
d webui
