#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")

if [ ! -f /etc/pki/CA/index.txt ]; then
    sudo mkdir --parents /etc/pki/CA
    sudo touch /etc/pki/CA/index.txt
fi

if [ ! -f /etc/pki/CA/serial ]; then
    sudo mkdir --parents /etc/pki/CA
    echo 1000 | sudo tee -a /etc/pki/CA/serial > /dev/null
fi

cd $HERE/work/dist/etc/freeDiameter

openssl req -new -batch -x509 -days 3650 -nodes -newkey rsa:2048 -out cacert.pem -keyout cakey.pem -subj /CN=ca.localdomain/C=KO/ST=Seoul/L=Nowon/O=Open5GS/OU=Tests

function gen () {
    openssl genrsa -out $1.key.pem 2048
    openssl req -new -batch -out $1.csr.pem -key $1.key.pem -subj /CN=$1.localdomain/C=KO/ST=Seoul/L=Nowon/O=Open5GS/OU=Tests
    sudo openssl ca -cert cacert.pem -days 3650 -keyfile cakey.pem -in $1.csr.pem -out $1.cert.pem -outdir . -batch
    rm $1.csr.pem
}

gen mme
gen hss
gen smf
gen pcrf

rm cakey.pem
