#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")

COMPONENT=$1

if [ "$COMPONENT" == mongo ]; then
    POD="open5gs-mongodb-0 --container=mongod"
else
    POD=$(kubectl get pods --selector="app.kubernetes.io/name=$COMPONENT" --output=jsonpath="{.items[0].metadata.name}")
fi

kubectl logs $POD "${@:2}"
