#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

TARBALL=$HERE/work/open5gs-container-image.tar

m 'deleting existing image...'
reposure image delete default "$OPEN5GS_IMAGE_TAG"
sleep 5

m 'exporting image to tarball...'
HOST=$(reposure registry info default host)
podman tag "localhost/$OPEN5GS_IMAGE_TAG" "$HOST/$OPEN5GS_IMAGE_TAG"
rm --force "$TARBALL"
podman save "$HOST/$OPEN5GS_IMAGE_TAG" --output "$TARBALL"

m 'publishing tarball...'
reposure image push default open5gs/open5gs "$TARBALL"
