#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

IP=$(kubectl get service webui --output=jsonpath='{.status.loadBalancer.ingress[0].ip}')
echo http://$IP
