tosca_definitions_version: tosca_simple_yaml_1_3

metadata:

  template_name: Open5GS SGWC Component

imports:

- file: ../profiles/open5gs/profile.yaml
  namespace_prefix: 5g
- file: ../profiles/open5gs-kubernetes/profile.yaml
  namespace_prefix: k8s

topology_template:

  inputs:

    component:
      type: string
      default: sgwc
    version:
      type: string
      default: 2.3.0
    registry:
      type: string
      default: docker.io
    namespace:
      type: string
      default: workspace

  node_templates:

    component:
      type: k8s:Component
      capabilities:
        service:
          properties:
            spec:
              ports:
              - name: gtpc # S11
                protocol: TCP
                targetPort: { port: 2123 }
                port: 2123
              - name: pfcp # Sxa
                protocol: TCP
                targetPort: { port: 8805 }
                port: 8805

  substitution_mappings:

    node_type: 5g:SGWC
