#!/bin/bash
set -e

if [ "$COMPONENT" == webui ]; then
    cd /opt/open5gs-webui
    npm run dev
    sleep infinity
else
    /bin/open5gs-${COMPONENT}d \
        -c /etc/open5gs/${COMPONENT}.yaml \
        -l /var/log/open5gs/${COMPONENT}.log \
        -e debug \
        -d
fi
