apiVersion: v1
kind: ServiceAccount

metadata:
  name: open5gs
  labels:
    app.kubernetes.io/version: $VERSION
    app.kubernetes.io/component: 5g
    app.kubernetes.io/part-of: open5gs
    app.kubernetes.io/managed-by: open5gs

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: open5gs
  labels:
    app.kubernetes.io/version: $VERSION
    app.kubernetes.io/component: 5g
    app.kubernetes.io/part-of: open5gs
    app.kubernetes.io/managed-by: open5gs

rules:
- apiGroups: [ "*" ]
  resources: [ "*" ]
  verbs: [ "*" ]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: open5gs
  #namespace: workspace # required
  labels:
    app.kubernetes.io/version: $VERSION
    app.kubernetes.io/component: 5g
    app.kubernetes.io/part-of: open5gs
    app.kubernetes.io/managed-by: open5gs

subjects:
- kind: ServiceAccount
  name: open5gs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: open5gs
